// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CurrentTime():Promise<string>;

export function KillProcess(arg1:number,arg2:string,arg3:number):Promise<main.KillResult>;

export function ListPorts():Promise<Array<main.PortInfo>>;

export function RelaunchAsAdministrator():Promise<void>;
