// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentTime() {
  return window['go']['main']['App']['CurrentTime']();
}

export function KillProcess(arg1, arg2, arg3) {
  return window['go']['main']['App']['KillProcess'](arg1, arg2, arg3);
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function RelaunchAsAdministrator() {
  return window['go']['main']['App']['RelaunchAsAdministrator']();
}
